# This allows it to run on faster containers.
sudo: false

language: python
python:
   - "2.7"
   - "3.3"
   - "3.4"
addons:
  apt:
    packages:
    - gcc
    - gfortran
# See http://conda.pydata.org/docs/travis.html
install:
  # You may want to periodically update this, although the conda update
  # conda line below will keep everything up-to-date.
  # This saves us some downloading for this version
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Should match requirements.txt
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION pip numpy scipy pandas matplotlib pytest
  - source activate test-environment
  # Build in place so we can run tests
  - python setup.py install
  - pip install coveralls
  - pip install pytest-cov
# command to run tests
script: py.test --cov lifelines -vv
after_success:
  coveralls debug
# Don't want notifications
notifications:
  email: false
