language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-scipy
install: "python setup.py install"
# command to run tests
script: python -m lifelines.tests.test_suite
