language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
    - sudo apt-get install -qq python-scipy python-numpy
# command to install dependencies
install: "python setup.py install"
# command to run tests
script: python -m unittest lifelines.tests.test_suite
